K Fold Cross Validation 

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

import numpy as np
from sklearn.datasets import load_digits


In [7]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
digits = load_digits()

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [16]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9666666666666667

In [17]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.987037037037037

In [18]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

In [21]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [22]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print("TRAIN:", train_index, "TEST:", test_index)

TRAIN: [3 4 5 6 7 8] TEST: [0 1 2]
TRAIN: [0 1 2 6 7 8] TEST: [3 4 5]
TRAIN: [0 1 2 3 4 5] TEST: [6 7 8]


In [28]:
from sklearn.model_selection import StratifiedKFold

In [33]:
fold = StratifiedKFold(n_splits=3)
fold

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [39]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [56]:
score_lr = []
score_svm = []
score_rf = []

for train_index, test_index in fold.split(digits.data, digits.target):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]

    score_lr.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test))

In [57]:
score_lr

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [58]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [59]:
score_rf

[0.9398998330550918, 0.9515859766277128, 0.9282136894824707]

In [60]:
from sklearn.model_selection import cross_val_score

In [62]:
cross_val_score(LogisticRegression(), digits.data, digits.target, cv=3)

array([0.92153589, 0.94156928, 0.91652755])

In [63]:
cross_val_score(SVC(), digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [64]:
from sklearn.datasets import load_iris
iris = load_iris()

In [65]:
cross_val_score(LogisticRegression(), iris.data, iris.target, cv=3)

array([0.98, 0.96, 0.98])

In [67]:
cross_val_score(SVC(), iris.data, iris.target, cv=3)

array([0.96, 0.98, 0.94])

In [68]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=3)

array([0.98, 0.94, 0.96])

In [73]:
score_lr = []
score_svm = []
score_rf = []

for train_index, test_index in fold.split(iris.data, iris.target):
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]

    print(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

0.98
0.94
0.96
